### ISSUE TITLE
org-block-background is light in dark theme

### ISSUE THREAD

**Issue by wdenton** [sellout/emacs-color-theme-solarized#144]
This started a couple of weeks ago: the background on source code blocks in Org is light even though I'm using the dark theme. It used to be the default dark background colour. 

It looks like this:

![solarized-problem](https://cloud.githubusercontent.com/assets/54162/5994001/4f58b832-aa32-11e4-816d-06c16c68ac24.png)

My eyes! My eyes!

`M-x describe-face` in a block says:

```
Face: org-block-background (sample) (customize this face)

Documentation:
Face used for the source block background.

Defined in `org-faces.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #eee8d5
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```

In `solarized-definitions.el` I see that #eee8d5 is part of base2, light colours, but also that `(org-block-background (,@bg-base02))` sets the background colour to a different colour, which should be dark, and then I don't know exactly what or where the problem is---here or in Org?

**Comment by sellout** [comment]
Ack, sorry. This is my fault. In 3f9e5470fcd10bda0c15345b8264eb332157477f I added a face for this (at someone else’s request, since I don’t use org-mode … yet), but I messed up and used `base02` when it should have been `base2`. I’ll get that fixed ASAP.

**Comment by sellout** [comment]
Wait … no, I’m confused. `base02` is right, so I’m not sure why it’s using the `base2` face for you in that one case. I’ll play with this a bit …

**Comment by wdenton** [comment]
Thanks. Let me know if I can try something out. That commit must be when the change started for me.

**Comment by wdenton** [comment]
There's a related Org face issue I just noticed, and again I don't know if this is a theme issue or triggered by something in Org, but it didn't happen a while ago. When I show a list of all TODOs in a file (C-c / t) it looks like this:

![solarized-again](https://cloud.githubusercontent.com/assets/54162/6023287/bac48cbc-ab91-11e4-8f76-5840bbe3aac9.png)

The three stars followed by a Unicode circle is coming from org-bullets and would probably look all right if the colours were OK, so I think we can set that aside. It's the bright colour that's odd.

M-x describe-face while on a bright bit says:

```
Face: secondary-selection (sample) (customize this face)

Documentation: 
Basic face for displaying the secondary selection.

Defined in `faces.el'.

           Family: unspecified
          Foundry: unspecified
            Width: unspecified
           Height: unspecified
           Weight: unspecified
            Slant: unspecified
       Foreground: unspecified
DistantForeground: unspecified
       Background: #eee8d5
        Underline: unspecified
         Overline: unspecified
   Strike-through: unspecified
              Box: unspecified
          Inverse: unspecified
          Stipple: unspecified
             Font: unspecified
          Fontset: unspecified
          Inherit: unspecified
```
