### ISSUE TITLE
Solarized Light has slightly darker background in terminal

### ISSUE THREAD

**Issue by aniranc** [sellout/emacs-color-theme-solarized#208]
Hi,

I'm using Solarized Light in both my terminal emulator (with `TERM=xterm-16color`) and emacs. The colors mostly look fine, but the background in terminal emacs is a darker shade of the regular Solarized Light background color.

GUI emacs' colors are fine. This discoloration happens in both `gnome-terminal` and Mac's `Terminal.app` through ssh. Any suggestions for troubleshooting?

Terminal outside emacs:
<img width="650" alt="screen shot 2018-05-22 at 8 40 57 pm" src="https://user-images.githubusercontent.com/4604619/40397399-86b39df8-5e00-11e8-8d12-af9079331165.png">

Terminal emacs:
<img width="647" alt="screen shot 2018-05-22 at 8 41 21 pm" src="https://user-images.githubusercontent.com/4604619/40397406-957b4458-5e00-11e8-9bd5-1e6437e0f12f.png">

`M-x describe-face` output:
```
Face: default (sample) (customize this face)                                                            
                                                                                                        
Documentation:                                                                                          
Basic default face.                                                                                     
                                                                                                        
           Family: default                                                                              
          Foundry: default                                                                              
            Width: normal                                                                               
           Height: 1                                                                                    
           Weight: normal                                                                               
            Slant: normal                                                                               
       Foreground: #657b83                                                                              
DistantForeground: unspecified                                                                          
       Background: #fdf6e3                                                                              
        Underline: nil                                                                                  
         Overline: nil                                                                                  
   Strike-through: nil                                                                                  
              Box: nil                                                                                  
          Inverse: nil                                                                                  
          Stipple: nil                                                                                  
             Font: unspecified                                                                          
          Fontset: nil                                                                                  
          Inherit: nil
```

`M-x version` output:
```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.24), modified by Debian
```

`M-: (display-color-cells)` output:
`16 (#o20, #x10, ?\C-p)`
